Pruzhinina
siriusdevs/rpm-hws_7-2_2023 pull request #11
Opened 2023-03-24 02:00 UTC by arinapruzhinina

2023-03-27 18:24 UTC, siriusdevs commented
your script doesnt work, did you even check it?

2023-03-27 18:25 UTC, siriusdevs requested changes

2023-03-27 18:25 UTC, siriusdevs commented on hw_quiz/script.sh
> +export PG_PASSWORD=123
are you sure?

2023-03-27 19:02 UTC, arinapruzhinina commented on hw_quiz/script.sh
> +export PG_PASSWORD=123
fixed

2023-03-30 00:18 UTC, siriusdevs commented
1) if i input the wrong type of answer (for example, text instead of a number), you tell me its wrong. then i proceed with answering "нет" on a question "Хотите сыграть ещё раз?". Nevertheless, the game continues..
2) if i input the wrong answer (for example, 1 instead of 2), this question will reappear until i will eventually give the right answer.

2023-04-02 10:31 UTC, merged