Kulgavykh
siriusdevs/rpm-hws_7-2_2023 pull request #5
Opened 2023-03-22 11:34 UTC by blinmakersha

First HW.

2023-03-22 21:27 UTC, siriusdevs requested changes
fix initializing script and readme

2023-03-22 21:27 UTC, siriusdevs commented on .DS_Store
this should be ignored with .gitignore

2023-03-22 21:27 UTC, siriusdevs commented on .github/workflows/pylint.yml.save
better delete this file

2023-03-22 21:27 UTC, siriusdevs commented on .gitignore
> +*.env*
*DS_Store*

2023-03-22 21:27 UTC, siriusdevs commented on QuizGame/README.md
> +    run init_script.sh
firstly
`chmod +x init_script.sh`
then
`./init_script.sh`

2023-03-22 21:27 UTC, siriusdevs commented on QuizGame/README.md
> +    run init_script.sh
Also, you init_script.sh asks password for db to finish. you can [fix this](https://stackoverflow.com/questions/6523019/postgresql-scripting-psql-execution-with-password) or just change the script logic

2023-03-22 21:27 UTC, siriusdevs commented on QuizGame/README.md
> +    HOST - database host
how do i know this creds? you set docker pg up yourself with your script.
maybe you could set up .env file in that script too?

2023-03-23 08:47 UTC, blinmakersha commented
Made some changes.

2023-03-23 11:30 UTC, siriusdevs requested changes
there is no Quiz result at the end of the game, which is sad. please kindly add some.

moreover, [banana is a language](https://github.com/KyleMiles/bananaScript) ! :smiley: 
just kidding

2023-03-23 11:30 UTC, siriusdevs commented on QuizGame/README.md
> +    cd quizgame
also, you do not have a directory named quizgame, it is QuizGame you have

2023-03-23 11:30 UTC, siriusdevs commented on QuizGame/README.md
> +    HOST - 127.0.0.1
you could actually just replace " - " with "=" and it would be a legitimate env file available for copying

2023-03-23 12:33 UTC, merged